In [12]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential, Model, load_model 
from tensorflow.keras.layers import Dense, Flatten, Input, concatenate, Conv2D, MaxPool2D, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import SGD, Adam, RMSprop
from tensorflow.keras.utils import to_categorical

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pyperclip

In [110]:
# 불러오기
result = pd.read_csv("data/돈까스_R01.csv")

In [111]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      1999 non-null   object
 1   ID            1999 non-null   object
 2   Contents      1999 non-null   object
 3   Tags          1790 non-null   object
 4   Tags_sum      1999 non-null   int64
 5   Tags_count    1999 non-null   int64
 6   Tags_rate     1999 non-null   float64
 7   Likes         1999 non-null   int64
 8   Scaled_likes  1999 non-null   float64
dtypes: float64(2), int64(3), object(4)
memory usage: 140.7+ KB

In [112]:
result["Tags"] = result["Tags"].fillna("")
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      1999 non-null   object
 1   ID            1999 non-null   object
 2   Contents      1999 non-null   object
 3   Tags          1999 non-null   object
 4   Tags_sum      1999 non-null   int64
 5   Tags_count    1999 non-null   int64
 6   Tags_rate     1999 non-null   float64
 7   Likes         1999 non-null   int64
 8   Scaled_likes  1999 non-null   float64
dtypes: float64(2), int64(3), object(4)
memory usage: 140.7+ KB

In [113]:
result

,Category,ID,Contents,Tags,Tags_sum,Tags_count,Tags_rate,Likes,Scaled_likes
0,돈까스,bbo_muksta,내 꿈은 돈모아서 돈까스의집 사는것 한입에 모든걸 뺏겨버린 맛이다 괜히 40년...,"#돈까스의집, #돈까스맛집, #송파맛집, #삼전역맛집, #빵맛집, #돈까스",6,8,133.33,3126,0.396449
1,돈까스,___foodtour,구름같은 만두를 맛볼 수 있은 곳이에요 너무 맛있어서 음소거 모드로 흡입했어요 ...,"#건대, #성수완당깔끔한, #투어_건대",3,1,33.33,3750,0.475587
2,돈까스,mukpresident,고치돈 좋아하는 국민들 주목 친애하는 국민여러분 먹통령입니다 오늘 저희가 회담을...,"#사장님돈까스, #먹통령_이대, #이대맛집, #이화여대맛집, #고치돈맛집, #돈까스...",8,10,125.00,2761,0.350159
3,돈까스,fooseidon_,다들주목 서울 3대 돈까스 오픈부터 엄청나게 웨이팅이 있는곳벼루다 드뎌...,"#북천, #북천돈까스🔱11:00~19:30, #푸세이돈_용...",18,0,0.00,7885,1.000000
4,돈까스,cayeongmi9,치즈돈까스 집에서만들기 육전용 돈등심으로 미니치즈돈까스를 만들었어요 등심에...,"#치즈돈까스, #집에서만들기, #키마카레, #미니돈까스, #사평카레, #저수분카레,...",19,8,42.11,317,0.040203
...,...,...,...,...,...,...,...,...,...
1994,돈까스,_ahromi,같이 있는 시간은 편하고돈까스는 맛있고 화요일 화요일저녁 반가워 명란바질파스...,"#화요일, #화요일저녁, #반가워, #명란바질파스타, #돈까스",5,1,20.00,8,0.001015
1995,돈까스,milk.emo,오늘 점심은 뭐먹을까 하셔서돈가스요 매일 꼬기 먹는데 안질리냐고 꼬기가 왜질려...,"#쑝쑝, #일상, #점심메뉴, #오늘은뭐먹지, #돈까스, #김치우동, #매일먹어도안...",10,3,30.00,19,0.002410
1996,돈까스,s0_0xn,성수맛집 성수떡볶이 해피치즈스마일 성수 떡볶이 돈까스,"#성수맛집, #성수떡볶이, #해피치즈스마일, #성수, #떡볶이, #돈까스",6,5,83.33,16,0.002029
1997,돈까스,gh_loveshj,영광맛집 미소야영광점 우동 모밀 돈까스 알밥 덮밥,"#영광맛집, #미소야영광점, #우동, #모밀, #돈까스, #알밥, #덮밥",7,2,28.57,22,0.002790
1998,돈까스,lee_d_n,안양에서 맛있게 먹었던 드림카츠가제주 산방산 아래서 새시작을 하신다기에바로 달려가봤...,"#제주, #서귀포, #서귀포맛집, #안덕면, #산방산, #드림카츠, #반반카츠, #...",12,3,25.00,41,0.005200

In [114]:
from tqdm.notebook import tqdm

example_list = ['돈까스', '맛집', '먹스타그램', '돈까스맛집', '00', '수', '맛스타그램', '돈카츠', '돈', '더',
       '일상', '점심', '너무', '11', '있는', '30', '잘', '1', '먹스타', '다', '많이',
       '집밥', '돈가스', '치즈돈까스', '맞팔', '한', '먹고', '정말', '먹방', '진짜'] # 밑에 워드클라우드 전처리과정에서 빈도수 상위30개 추출
Tags_count = [ ]
for i in tqdm(range(len(result))):
    text=[]
    sentence = result["Tags"].str.split("#")[i][1:]
    for s in range(len(sentence)):
        if "," in sentence[s]:
            text.append(sentence[s][:-2])
        else:
            text.append(sentence[s])

    tmp=0
    for j in range(len(example_list)):
        tmp += sum(map(lambda x : 1 if x == example_list[j] else 0, text))
    Tags_count.append(tmp)

result["Tags_count"] = Tags_count

  0%|          | 0/1999 [00:00<?, ?it/s]

In [115]:
result

,Category,ID,Contents,Tags,Tags_sum,Tags_count,Tags_rate,Likes,Scaled_likes
0,돈까스,bbo_muksta,내 꿈은 돈모아서 돈까스의집 사는것 한입에 모든걸 뺏겨버린 맛이다 괜히 40년...,"#돈까스의집, #돈까스맛집, #송파맛집, #삼전역맛집, #빵맛집, #돈까스",6,2,133.33,3126,0.396449
1,돈까스,___foodtour,구름같은 만두를 맛볼 수 있은 곳이에요 너무 맛있어서 음소거 모드로 흡입했어요 ...,"#건대, #성수완당깔끔한, #투어_건대",3,0,33.33,3750,0.475587
2,돈까스,mukpresident,고치돈 좋아하는 국민들 주목 친애하는 국민여러분 먹통령입니다 오늘 저희가 회담을...,"#사장님돈까스, #먹통령_이대, #이대맛집, #이화여대맛집, #고치돈맛집, #돈까스...",8,2,125.00,2761,0.350159
3,돈까스,fooseidon_,다들주목 서울 3대 돈까스 오픈부터 엄청나게 웨이팅이 있는곳벼루다 드뎌...,"#북천, #북천돈까스🔱11:00~19:30, #푸세이돈_용...",18,0,0.00,7885,1.000000
4,돈까스,cayeongmi9,치즈돈까스 집에서만들기 육전용 돈등심으로 미니치즈돈까스를 만들었어요 등심에...,"#치즈돈까스, #집에서만들기, #키마카레, #미니돈까스, #사평카레, #저수분카레,...",19,3,42.11,317,0.040203
...,...,...,...,...,...,...,...,...,...
1994,돈까스,_ahromi,같이 있는 시간은 편하고돈까스는 맛있고 화요일 화요일저녁 반가워 명란바질파스...,"#화요일, #화요일저녁, #반가워, #명란바질파스타, #돈까스",5,1,20.00,8,0.001015
1995,돈까스,milk.emo,오늘 점심은 뭐먹을까 하셔서돈가스요 매일 꼬기 먹는데 안질리냐고 꼬기가 왜질려...,"#쑝쑝, #일상, #점심메뉴, #오늘은뭐먹지, #돈까스, #김치우동, #매일먹어도안...",10,2,30.00,19,0.002410
1996,돈까스,s0_0xn,성수맛집 성수떡볶이 해피치즈스마일 성수 떡볶이 돈까스,"#성수맛집, #성수떡볶이, #해피치즈스마일, #성수, #떡볶이, #돈까스",6,1,83.33,16,0.002029
1997,돈까스,gh_loveshj,영광맛집 미소야영광점 우동 모밀 돈까스 알밥 덮밥,"#영광맛집, #미소야영광점, #우동, #모밀, #돈까스, #알밥, #덮밥",7,1,28.57,22,0.002790
1998,돈까스,lee_d_n,안양에서 맛있게 먹었던 드림카츠가제주 산방산 아래서 새시작을 하신다기에바로 달려가봤...,"#제주, #서귀포, #서귀포맛집, #안덕면, #산방산, #드림카츠, #반반카츠, #...",12,2,25.00,41,0.005200

In [116]:
result["Tags_rate"] = ((result["Tags_count"] / result["Tags_sum"]) * 100) .round(2)
result

,Category,ID,Contents,Tags,Tags_sum,Tags_count,Tags_rate,Likes,Scaled_likes
0,돈까스,bbo_muksta,내 꿈은 돈모아서 돈까스의집 사는것 한입에 모든걸 뺏겨버린 맛이다 괜히 40년...,"#돈까스의집, #돈까스맛집, #송파맛집, #삼전역맛집, #빵맛집, #돈까스",6,2,33.33,3126,0.396449
1,돈까스,___foodtour,구름같은 만두를 맛볼 수 있은 곳이에요 너무 맛있어서 음소거 모드로 흡입했어요 ...,"#건대, #성수완당깔끔한, #투어_건대",3,0,0.00,3750,0.475587
2,돈까스,mukpresident,고치돈 좋아하는 국민들 주목 친애하는 국민여러분 먹통령입니다 오늘 저희가 회담을...,"#사장님돈까스, #먹통령_이대, #이대맛집, #이화여대맛집, #고치돈맛집, #돈까스...",8,2,25.00,2761,0.350159
3,돈까스,fooseidon_,다들주목 서울 3대 돈까스 오픈부터 엄청나게 웨이팅이 있는곳벼루다 드뎌...,"#북천, #북천돈까스🔱11:00~19:30, #푸세이돈_용...",18,0,0.00,7885,1.000000
4,돈까스,cayeongmi9,치즈돈까스 집에서만들기 육전용 돈등심으로 미니치즈돈까스를 만들었어요 등심에...,"#치즈돈까스, #집에서만들기, #키마카레, #미니돈까스, #사평카레, #저수분카레,...",19,3,15.79,317,0.040203
...,...,...,...,...,...,...,...,...,...
1994,돈까스,_ahromi,같이 있는 시간은 편하고돈까스는 맛있고 화요일 화요일저녁 반가워 명란바질파스...,"#화요일, #화요일저녁, #반가워, #명란바질파스타, #돈까스",5,1,20.00,8,0.001015
1995,돈까스,milk.emo,오늘 점심은 뭐먹을까 하셔서돈가스요 매일 꼬기 먹는데 안질리냐고 꼬기가 왜질려...,"#쑝쑝, #일상, #점심메뉴, #오늘은뭐먹지, #돈까스, #김치우동, #매일먹어도안...",10,2,20.00,19,0.002410
1996,돈까스,s0_0xn,성수맛집 성수떡볶이 해피치즈스마일 성수 떡볶이 돈까스,"#성수맛집, #성수떡볶이, #해피치즈스마일, #성수, #떡볶이, #돈까스",6,1,16.67,16,0.002029
1997,돈까스,gh_loveshj,영광맛집 미소야영광점 우동 모밀 돈까스 알밥 덮밥,"#영광맛집, #미소야영광점, #우동, #모밀, #돈까스, #알밥, #덮밥",7,1,14.29,22,0.002790
1998,돈까스,lee_d_n,안양에서 맛있게 먹었던 드림카츠가제주 산방산 아래서 새시작을 하신다기에바로 달려가봤...,"#제주, #서귀포, #서귀포맛집, #안덕면, #산방산, #드림카츠, #반반카츠, #...",12,2,16.67,41,0.005200

In [119]:
result["Tags_rate"] = result["Tags_rate"].fillna(0)
result["Tags_rate"]

0       33.33
1        0.00
2       25.00
3        0.00
4       15.79
        ...
1994    20.00
1995    20.00
1996    16.67
1997    14.29
1998    16.67
Name: Tags_rate, Length: 1999, dtype: float64

In [120]:
len_list=[]

for i in range(1999):
    len_t=len(result["Contents"][i])
    len_list.append(len_t)
    
result["Contents_len"] = len_list
result

,Category,ID,Contents,Tags,Tags_sum,Tags_count,Tags_rate,Likes,Scaled_likes,Contents_len
0,돈까스,bbo_muksta,내 꿈은 돈모아서 돈까스의집 사는것 한입에 모든걸 뺏겨버린 맛이다 괜히 40년...,"#돈까스의집, #돈까스맛집, #송파맛집, #삼전역맛집, #빵맛집, #돈까스",6,2,33.33,3126,0.396449,377
1,돈까스,___foodtour,구름같은 만두를 맛볼 수 있은 곳이에요 너무 맛있어서 음소거 모드로 흡입했어요 ...,"#건대, #성수완당깔끔한, #투어_건대",3,0,0.00,3750,0.475587,467
2,돈까스,mukpresident,고치돈 좋아하는 국민들 주목 친애하는 국민여러분 먹통령입니다 오늘 저희가 회담을...,"#사장님돈까스, #먹통령_이대, #이대맛집, #이화여대맛집, #고치돈맛집, #돈까스...",8,2,25.00,2761,0.350159,634
3,돈까스,fooseidon_,다들주목 서울 3대 돈까스 오픈부터 엄청나게 웨이팅이 있는곳벼루다 드뎌...,"#북천, #북천돈까스🔱11:00~19:30, #푸세이돈_용...",18,0,0.00,7885,1.000000,469
4,돈까스,cayeongmi9,치즈돈까스 집에서만들기 육전용 돈등심으로 미니치즈돈까스를 만들었어요 등심에...,"#치즈돈까스, #집에서만들기, #키마카레, #미니돈까스, #사평카레, #저수분카레,...",19,3,15.79,317,0.040203,393
...,...,...,...,...,...,...,...,...,...,...
1994,돈까스,_ahromi,같이 있는 시간은 편하고돈까스는 맛있고 화요일 화요일저녁 반가워 명란바질파스...,"#화요일, #화요일저녁, #반가워, #명란바질파스타, #돈까스",5,1,20.00,8,0.001015,52
1995,돈까스,milk.emo,오늘 점심은 뭐먹을까 하셔서돈가스요 매일 꼬기 먹는데 안질리냐고 꼬기가 왜질려...,"#쑝쑝, #일상, #점심메뉴, #오늘은뭐먹지, #돈까스, #김치우동, #매일먹어도안...",10,2,20.00,19,0.002410,133
1996,돈까스,s0_0xn,성수맛집 성수떡볶이 해피치즈스마일 성수 떡볶이 돈까스,"#성수맛집, #성수떡볶이, #해피치즈스마일, #성수, #떡볶이, #돈까스",6,1,16.67,16,0.002029,35
1997,돈까스,gh_loveshj,영광맛집 미소야영광점 우동 모밀 돈까스 알밥 덮밥,"#영광맛집, #미소야영광점, #우동, #모밀, #돈까스, #알밥, #덮밥",7,1,14.29,22,0.002790,33
1998,돈까스,lee_d_n,안양에서 맛있게 먹었던 드림카츠가제주 산방산 아래서 새시작을 하신다기에바로 달려가봤...,"#제주, #서귀포, #서귀포맛집, #안덕면, #산방산, #드림카츠, #반반카츠, #...",12,2,16.67,41,0.005200,169

In [121]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Category      1999 non-null   object
 1   ID            1999 non-null   object
 2   Contents      1999 non-null   object
 3   Tags          1999 non-null   object
 4   Tags_sum      1999 non-null   int64
 5   Tags_count    1999 non-null   int64
 6   Tags_rate     1999 non-null   float64
 7   Likes         1999 non-null   int64
 8   Scaled_likes  1999 non-null   float64
 9   Contents_len  1999 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 156.3+ KB

In [122]:
# 저장
result.to_csv("data/돈까스_R02.csv", encoding="utf-8", index=False)